name: puggernaut
version: 0.2.1
authors:
  - Winton Welsh
email: mail@wintoni.us
homepage: http://github.com/winton/puggernaut
summary: Simple server push implementation using eventmachine and long polling
description: Simple server push implementation using eventmachine and long polling
dependencies:
  - em-websocket
  - eventmachine
  - memprof
development_dependencies: null