name: puggernaut
version: 0.1.0
authors:
  - Winton Welsh
email: mail@wintoni.us
homepage: http://github.com/winton/puggernaut
summary: Simple server push implementation using eventmachine and long polling
description: Simple server push implementation using eventmachine and long polling
dependencies:
  - eventmachine
development_dependencies: null